import { StyleSheet } from "react-native";

export const colors = {
    background: "#f4f7fb",
    surface: "#ffffff",
    text: "#111827",
    muted: "#6b7280",
    border: "#dbe3ef",
    primary: "#2563eb",
    primaryDark: "#1e40af",
    danger: "#dc2626",
    dark: "#111827",
    disabled: "#9ca3af",
};

export const ui = StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: colors.background,
    },
    content: {
        flex: 1,
        padding: 20,
    },
    scrollContent: {
        padding: 20,
        paddingBottom: 32,
    },
    authContent: {
        flexGrow: 1,
        justifyContent: "center",
        padding: 20,
    },
    centeredScreen: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: colors.background,
        padding: 20,
    },
    title: {
        color: colors.text,
        fontSize: 28,
        fontWeight: "800",
        marginBottom: 6,
    },
    subtitle: {
        color: colors.muted,
        fontSize: 15,
        lineHeight: 22,
        marginBottom: 20,
    },
    sectionTitle: {
        color: colors.text,
        fontSize: 17,
        fontWeight: "700",
        marginBottom: 10,
    },
    card: {
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 14,
        padding: 16,
        marginBottom: 14,
        shadowColor: "#000000",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
        elevation: 2,
    },
    authCard: {
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 18,
        padding: 20,
        shadowColor: "#000000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 3,
    },
    cardTitle: {
        color: colors.text,
        fontSize: 19,
        fontWeight: "800",
        marginBottom: 8,
    },
    bodyText: {
        color: colors.text,
        fontSize: 15,
        lineHeight: 22,
    },
    metaText: {
        color: colors.muted,
        fontSize: 14,
        lineHeight: 21,
        marginTop: 4,
    },
    label: {
        color: colors.text,
        fontSize: 14,
        fontWeight: "700",
        marginBottom: 6,
    },
    input: {
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 12,
        color: colors.text,
        fontSize: 16,
        paddingHorizontal: 14,
        paddingVertical: 12,
        marginBottom: 14,
    },
    button: {
        backgroundColor: colors.primary,
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 16,
        alignItems: "center",
        justifyContent: "center",
        marginTop: 12,
    },
    buttonDark: {
        backgroundColor: colors.dark,
    },
    buttonDanger: {
        backgroundColor: colors.danger,
    },
    buttonDisabled: {
        backgroundColor: colors.disabled,
    },
    buttonText: {
        color: colors.surface,
        fontSize: 15,
        fontWeight: "800",
        textAlign: "center",
    },
    linkButton: {
        paddingVertical: 14,
        alignItems: "center",
        justifyContent: "center",
    },
    linkText: {
        color: colors.primary,
        fontSize: 15,
        fontWeight: "700",
        textAlign: "center",
    },
    topActions: {
        flexDirection: "row",
        justifyContent: "flex-end",
        marginBottom: 18,
        gap: 8,
    },
    smallButton: {
        backgroundColor: colors.primary,
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 10,
    },
    smallButtonText: {
        color: colors.surface,
        fontSize: 13,
        fontWeight: "800",
        textAlign: "center",
    },
    homeButton: {
        alignSelf: "flex-start",
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 10,
        marginBottom: 14,
    },
    homeButtonText: {
        color: colors.primary,
        fontSize: 13,
        fontWeight: "800",
        textAlign: "center",
    },
    errorCard: {
        backgroundColor: "#fff1f2",
        borderWidth: 1,
        borderColor: "#fecdd3",
        borderRadius: 14,
        padding: 16,
    },
    errorText: {
        color: "#9f1239",
        fontSize: 15,
        lineHeight: 22,
    },
    emptyState: {
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 14,
        padding: 20,
    },
    loadingText: {
        color: colors.muted,
        fontSize: 16,
        fontWeight: "600",
    },
    detailText: {
        color: colors.text,
        fontSize: 15,
        lineHeight: 22,
        marginTop: 6,
    },
    totalText: {
        color: colors.text,
        fontSize: 18,
        fontWeight: "800",
    },
    stepperCard: {
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 14,
        padding: 14,
        marginBottom: 20,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    stepperButton: {
        width: 46,
        height: 46,
        borderRadius: 23,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: colors.dark,
    },
    stepperButtonDisabled: {
        backgroundColor: "#e5e7eb",
    },
    stepperButtonText: {
        color: colors.surface,
        fontSize: 24,
        fontWeight: "800",
    },
    stepperButtonTextDisabled: {
        color: colors.disabled,
    },
    guestCount: {
        color: colors.text,
        fontSize: 24,
        fontWeight: "800",
    },
});
